### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by barafael** [tbrand/cargo-tomlfmt#16]
First of all, thanks for this crate! This is a fairly important and good tool in the Rust toolbelt and Continuous Integration world.

I was wondering about the maintenance status. It works reliably as of now, but there seem to be a few issues that could easily be fixed, and the dependencies could be updated. I submitted one PR a while ago and could do some more, just wanna know if you are still interested in this thing :)

Edit: Also for some reason, the README.md isn't showing on crates.io, which could probably be easily fixed

**Comment by tbrand** [comment]
Hi @barafael, thanks for using this crate. Unfortunately, I don't have room to maintain this repository now. If you would like to do something with this, I could add you as a collaborator. Regards.

**Comment by barafael** [comment]
I'd love to occasionally look over it and make sure it builds fine etc.

**Comment by tbrand** [comment]
Thanks. Added you as a collaborator.
