### ISSUE TITLE
Preserve comments

### ISSUE THREAD

**Issue by regexident** [tbrand/cargo-tomlfmt#5]
Hi Taichiro,

very handy tool!

It currently does not preserve comments though. 😟

There is the [toml_edit](https://docs.rs/toml_edit/0.1.3/toml_edit/index.html) crate, which has comment-preservation and editing capabilities specifically for the purpose of programmatically editing `Cargo.toml` (via cargo-edit, e.g.), btw.

**Comment by tbrand** [comment]
Thanks for the info! Will check the implementation. :)

**Comment by tbrand** [comment]
I switched the main parser to toml_edit. Thanks for the suggestion! :+1:
https://github.com/tbrand/cargo-tomlfmt/pull/6
