### ISSUE TITLE
Get file as input

### ISSUE THREAD

**Issue by sagiegurari** [tbrand/cargo-tomlfmt#8]
Really like the idea of this crate.
Would it be possible to default to Cargo.toml but also allow to provide a file name/regex/dir to enable formatting other toml files?
If I can format other toml files I have, I can start using this crate.

**Comment by tbrand** [comment]
Thanks for the feedback.
Currently, name (You can by an option!) regex (You can't!) dir (You can't!).
But it can be fixed.
I'll work on it when I have times or pull requests are welcome. :)

**Comment by sagiegurari** [comment]
works good. thanks. 
the -p is simply not documented.
